net start "Datto RMM"
net start "CagService"
net start "SQL Server (MSSQLSERVER)" 
net start "OpalRad ImageServer"
net start "OpalRad Dicom Print"
net start "OpalRad DICOM Receive"
net start "OpalRad Listener"
net start "OpalRad Router"
net start "Opal Agent"
net start "Opal Backup"
net start "OpalRad Modality Worklist"
net start "World Wide Web Publishing Service"
net start "Code42 CrashPlan Backup Service"